version: '3.1'

services:

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_USER: bookUser
      MYSQL_PASSWORD: password1
      MYSQL_ROOT_PASSWORD: rootpassword1
      MYSQL_DATABASE: mybook
    ports:
      - "3306:3306"